
-- Operational errors generated by n8n/backend webhooks.
CREATE TABLE IF NOT EXISTS public.n8n_error_logs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  execution_id TEXT NOT NULL UNIQUE,
  workflow_name TEXT NOT NULL,
  message TEXT NOT NULL,
  node TEXT,
  execution_url TEXT,
  client_id TEXT,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  resolved BOOLEAN NOT NULL DEFAULT false,
  resolved_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_n8n_error_logs_client_id
  ON public.n8n_error_logs (client_id);

CREATE INDEX IF NOT EXISTS idx_n8n_error_logs_created_at
  ON public.n8n_error_logs (created_at DESC);

-- Operational notifications shown in the CRM.
CREATE TABLE IF NOT EXISTS public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  type TEXT NOT NULL DEFAULT 'system',
  title TEXT NOT NULL,
  description TEXT,
  link TEXT,
  read BOOLEAN NOT NULL DEFAULT false,
  client_id TEXT,
  user_id TEXT
);

ALTER TABLE public.notifications
  ADD COLUMN IF NOT EXISTS client_id TEXT,
  ADD COLUMN IF NOT EXISTS user_id TEXT;

CREATE INDEX IF NOT EXISTS idx_notifications_client_id
  ON public.notifications (client_id);

CREATE INDEX IF NOT EXISTS idx_notifications_user_id
  ON public.notifications (user_id);

CREATE INDEX IF NOT EXISTS idx_notifications_unread_created_at
  ON public.notifications (read, created_at DESC);

-- Block all direct access to n8n_error_logs (only rotas Express with service_role can access)
ALTER TABLE public.n8n_error_logs ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'n8n_error_logs'
      AND policyname = 'Deny all direct access to n8n_error_logs'
  ) THEN
    CREATE POLICY "Deny all direct access to n8n_error_logs"
    ON public.n8n_error_logs
    FOR ALL
    USING (false);
  END IF;
END $$;

-- Block all direct access to notifications (only rotas Express with service_role can access)
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename = 'notifications'
      AND policyname = 'Deny all direct access to notifications'
  ) THEN
    CREATE POLICY "Deny all direct access to notifications"
    ON public.notifications
    FOR ALL
    USING (false);
  END IF;
END $$;
