ALTER TABLE public.leads_outlier
  ADD COLUMN IF NOT EXISTS cidade TEXT,
  ADD COLUMN IF NOT EXISTS estado TEXT,
  ADD COLUMN IF NOT EXISTS interesse TEXT,
  ADD COLUMN IF NOT EXISTS objetivo TEXT,
  ADD COLUMN IF NOT EXISTS credito TEXT,
  ADD COLUMN IF NOT EXISTS parcela TEXT,
  ADD COLUMN IF NOT EXISTS prazo TEXT,
  ADD COLUMN IF NOT EXISTS lance_entrada_fgts TEXT,
  ADD COLUMN IF NOT EXISTS experiencia_consorcio TEXT,
  ADD COLUMN IF NOT EXISTS motivacao TEXT,
  ADD COLUMN IF NOT EXISTS decisor TEXT,
  ADD COLUMN IF NOT EXISTS melhor_horario TEXT;

ALTER TABLE public.leads_teste
  ADD COLUMN IF NOT EXISTS interesse TEXT,
  ADD COLUMN IF NOT EXISTS objetivo TEXT,
  ADD COLUMN IF NOT EXISTS credito TEXT,
  ADD COLUMN IF NOT EXISTS parcela TEXT,
  ADD COLUMN IF NOT EXISTS prazo TEXT,
  ADD COLUMN IF NOT EXISTS lance_entrada_fgts TEXT,
  ADD COLUMN IF NOT EXISTS experiencia_consorcio TEXT,
  ADD COLUMN IF NOT EXISTS motivacao TEXT,
  ADD COLUMN IF NOT EXISTS decisor TEXT,
  ADD COLUMN IF NOT EXISTS melhor_horario TEXT;
